### ISSUE TITLE
Unsupported Type - payment callbacks

### ISSUE THREAD

**Issue by DeH4eG** [semyonchetvertnyh/omnipay-paysera#7]
Can't find any reference in Paysera docs - https://developers.paysera.com/en/checkout/integrations/integration-callback

Is this check necessary at all?
If not, i can make pull request

https://github.com/semyonchetvertnyh/omnipay-paysera/blob/a6597230360e47ab50bc566f6dd7a81b1e611955/src/Message/AcceptNotificationResponse.php#L25

**Comment by vlados** [comment]
I am having the same issue

**Comment by vlados** [comment]
Checkout https://github.com/arbory/omnipay-paysera

**Comment by DeH4eG** [comment]
Thank you for answer 👍🏽
